dataset:
  labels:
    negative: Non-pCR
    positive: pCR

  time_points:
    - T0
    - T1
    - T2

  modalities:
    - ADC 0100600800

  masks:
    - DWI MASK

pipeline:
  features_transformer:
    radiomics:
      encoders: # encoder names format is {time point}_{image}
        - image: ADC 0100600800
          mask: DWI MASK
          time_points:
            - T0
            - T1
            - T2
      engine:
        imageType:
          Original: {}
        setting:
          resampledPixelSpacing:  [1.27,1.27,4.0]
  features_selection:
    k: 100
  classifier:
    module: xgboost.XGBClassifier
    parameters:
          random_state: 42
          use_label_encoder: False
          validate_parameters: True
          learning_rate: 0.01
          n_estimators: 1000
          max_depth: 20
          min_child_weight: 10

grid_search_cv:
  verbose: 3
  scoring: roc_auc
  cv: 5
  param_grid:
    classifier:
      scale_pos_weight:
        - 2.22 # balanced